Print out results of rake task on failure

diff --git a/marc-index b/marc-index
--- a/marc-index
+++ b/marc-index
@@ -35,10 +35,10 @@ fi
 
 # Copy the marc file for Blacklight
 if [ -e $REMOTEPATH ]; then
-	/bin/cp -f $REMOTEPATH $LOCALPATH
+  /bin/cp -f $REMOTEPATH $LOCALPATH
 else
-	echo "Marc file failed to download or was not found"
-	exit 1;
+  echo "Marc file failed to download or was not found"
+  exit 1;
 fi
 
 # Index it into blacklight
@@ -48,6 +48,7 @@ export RAILS_ENV=${RAILS_ENV}
 rake solr:marc:index MARC_FILE=$LOCALPATH >& $RAKEOUTPUT
 if [ "$?" -gt "0" ]; then
   echo "Rake task failed"
+  cat $RAKEOUTPUT
   exit 1;
 fi
 
